language: python
python:
  - "3.4"

before_install:
  - pip install coveralls coverage pyparsing

install:
  - python setup.py install

script:
 - coverage run -m unittest discover --start-directory test
 - coverage report -m

after_success:
 - coveralls

notifications:
  email: false
